/*
API Reference for 郵便番号・デジタルアドレス

Testing AddresszipAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package jpid

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/g1eng/jpid-go"
)

func Test_jpid_AddresszipAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AddresszipAPIService ApiV1AddresszipPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AddresszipAPI.ApiV1AddresszipPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
